"""Hilfetexte aus bzw. eng an den Kommentaren der Excel-Referenz Rev. 8."""

HELP = {
    "electrolyzer_power_kw": "Installierte elektrische Nennleistung des Elektrolyseurs.",
    "electrolyzer_invest_eur_per_kw": "Spezifische Investitionskosten des Elektrolyseurs bezogen auf seine installierte elektrische Leistung.",
    "avg_efficiency_h2_per_el": "Effizienz des Elektrolyseurs laut Hersteller. Dies ist keine Systemeffizienz.",
    "min_load_fraction": "Gibt die minimale Teillast des Elektrolyseursystems an. Unterhalb dieser Last wird das System abgeschaltet.",
    "peripheral_power_fraction": "Elektrischer Verbrauch der Peripherie relativ zum Elektrolyseurverbrauch. Im Excel wird daraus die installierte Systemleistung berechnet.",
    "bop_eur_per_kw": "Beinhaltet sämtliche Anlagenteile zur Elektrolyse außer dem Elektrolyseur selbst, z. B. Wasseraufbereitung und Rohrleitungen.",
    "battery_capacity_factor": "Faktor zwischen Speicherkapazität des Batteriespeichers und Leistung des Elektrolyseursystems. Im Excel entspricht die Systemleistung zugleich der maximalen Ausgangsleistung des Batteriesystems.",
    "waste_heat_enabled": "Auswählen, sobald die Abwärme des Elektrolyseurs als Nebenprodukt nutzbar gemacht wird. Weitere Berechnungen erfolgen automatisch im Modell.",
    "oxygen_enabled": "Auswählen, sobald der Sauerstoff des Elektrolyseurs als Nebenprodukt nutzbar gemacht wird. Die Verdichterarbeit und der mögliche Verkaufserlös werden dann automatisch berechnet.",
    "h2_processing": "Auswahl zur Aufbereitung des Wasserstoffs. Bei Verdichtung werden die technischen Verdichterparameter in die Systemleistung und den Stromverbrauch einbezogen.",
    "h2_compressor_work": "Isentrope Verdichterarbeit für Wasserstoff nach der Methodik des Excel-Referenzmodells.",
    "oxygen_compressor_work": "Isentrope Verdichterarbeit für Sauerstoff nach der Methodik des Excel-Referenzmodells.",
    "stack_lifetime_hours": "Technische Lebensdauer der Stacks in Betriebs- bzw. äquivalenten Volllaststunden.",
    "degradation_per_year": "Lineare Wirkungsgraddegradation der Stacks pro Jahr. Das Excel gibt diesen Wert aus technischen Gründen derzeit in %/a an.",
    "equity_interest_rate": "Fiktiver kalkulatorischer Zins für das Eigenkapital zur Abbildung der Opportunitätskosten.",
    "stack_replacement_share": "Kosten eines Stacktauschs als Anteil der spezifischen Investitionskosten des Elektrolyseurs.",
    "stack_cost_degression": "Jährliche Kostendegression der Stackersatzkosten durch erwartete Skaleneffekte.",
    "price_escalation": "Das Excel bildet aus Ausgangswert und jährlicher Preisentwicklung einen nominalen Mittelwert über die gesamte Projektlaufzeit.",
    "thg_quote": "Erlös aus der THG-Quote nach der im Excel hinterlegten Minderungsquoten- und Anrechnungslogik.",
    "section7": "Strombezug nach §7 Abs. 3 der 37. BImSchV. Im Excel wird stündlich geprüft, ob der Börsenpreis unter einer aus CO₂-Preis und internem Grenzwert abgeleiteten Schwelle liegt.",
    "section7_negative_prices": "Legt fest, ob negative Börsenpreise bei der §7-Prüfung unverändert berücksichtigt werden. Bei deaktivierter Option werden negative Preise für diese Prüfung auf 0 €/MWh gesetzt.",
    "section13k": "Strombezug nach §13k EnWG (Nutzen statt Abregeln). Die verfügbare Strommenge wird über eine stündliche Jahresreihe vorgegeben.",
    "power_privileges": "Befreiungen und Privilegierungen werden für Elektrolyseur und übrige Verbraucher getrennt berücksichtigt. Eine aktive Befreiung setzt den jeweiligen Stromnebenkostenbestandteil auf null.",
    "opex_lump_sum": "Auswahl, wenn die OPEX als Pauschale berechnet werden sollen. Der Prozentsatz bezieht sich im Excel auf die CAPEX nach CAPEX-Förderung; die detaillierte OPEX-Aufschlüsselung wird dann nicht für OPEX Total verwendet.",
    "capex_subsidy": "Auswahl der CAPEX-Förderung. Die Förderung wird automatisch mit den CAPEX verrechnet; für die Förderübersicht wird die Gesamtförderung gleichmäßig auf die Projektlaufzeit verteilt.",
    "opex_subsidy": "Auswahl der OPEX-Förderung nach produziertem kg H₂ oder äquivalenter Volllaststunde. Hinweis: Rev. 8 zieht sie nur im pauschalen OPEX-Modus tatsächlich von OPEX Total ab.",
    "electricity_subsidy": "Auswahl der Strompreisförderung nach produziertem kg H₂ oder verbrauchter MWh Systemstrom. Die Förderung wird direkt von den jährlichen Stromkosten abgezogen.",
    "spk": "Auswahl der Strompreiskompensation. Das Excel bietet die offizielle Rechnerlogik oder einen separat kalkulierten Jahresertrag; Preisentwicklungen werden über die Projektlaufzeit gemittelt.",
    "power_sale_enabled": "Aktiviert den Verkauf der nach Eigenverbrauch und Batterieladung verbleibenden Strommenge. Excel Rev. 8 erlaubt Spotmarkt oder einen PPA-Verkaufspreis.",
    "power_sale_mode": "Wahl der Erlösbewertung für überschüssigen Strom: stündlicher Spotmarktpreis oder fester PPA-Verkaufspreis. Negative Spotpreise werden im Excel einnahmeseitig auf null begrenzt.",
    "ppa_sale_price": "Heutiger PPA-Verkaufspreis für überschüssigen Strom. Die jährliche Verkaufspreisentwicklung wird wie im Excel über die Projektlaufzeit gemittelt.",
    "balancing_energy": "Regelenergie wird in Excel Rev. 8 nicht stündlich simuliert, sondern über einen extern kalkulierten Jahresertrag mit optionaler jährlicher Preisentwicklung angesetzt.",
    "other_revenues": "Aktiviert zwei getrennte sonstige Jahreserlöse. Beide Positionen können wie im Excel mit einer eigenen jährlichen Preisentwicklung versehen werden.",
}
